### ISSUE TITLE
CTD without error message

### ISSUE THREAD

**Issue by EaMS1234** [GLS-SSV/SSV#1]
Hi, I've installed the addon (v.1.0) following the instructions provided on **README.md**, but the game keep crashing without even showing an error message (I can assure the settings are properly set and the provided fonts are installed). Any idea of what could be crashing the sim? The same doesn't happens with the default vessels and the other addons I have installed.

[Orbiter.log](https://github.com/GLS-SSV/SSV/files/9363094/Orbiter.log)

I'm using Orbiter 2016 Beta v.190914 installed following [these instructions](http://orbit.medphys.ucl.ac.uk/betainstall.html) with these addons: AMSO, NASSP 8.0, BasesyncMFD, Glideslope and ModuleMessagingExtMFD, HD textures for Earth and Moon, Antelope scenery, D3D9 client, Surface Microtextures and OrbiterSound 5.0.

If relevant, my system specifications are:
- OS: Windows 11 21H2 22000.856
- CPU: Intel Core i3-9100F
- RAM: 16GB Dual Channel 2133 GHz
- GPU: NVIDIA GeForce GTX 1050 Ti (Game Ready Driver 516.59)
- DRIVE (wherethe game's installed): 1TB HDD
- DRIVE (where the OS's installed): 240GB M.2 SSD

If I've forgotten anything or if there are any other relevant logs and files needed, I'll upload them. Thanks in advance.

**Comment by GLS-SSV** [comment]
Hi!
The issue could be with another addon being installed, which is unlikely if you overwritten all files during SSV installation. Can you disable the other addon MFDs?
If that doesn't do it, then it could be because you are running Orbiter Beta and SSV was compiled for the released Orbiter 2016. Can you setup a "plain" Orbiter 2016 and try SSV there?

**Comment by EaMS1234** [comment]
Thanks for the quick response! Switching from Beta to _"Stable"_ worked. Sorry for the inconvenience and thanks for this amazing addon!
