### ISSUE TITLE
ODS Seen through objects ? (SSV 1.6)

### ISSUE THREAD

**Issue by Snaxist** [GLS-SSV/SSV#14]
When docking with a station, from the A8U window, I could see the ODS through the PMA of the canadian space station (addon by LordCroussette), something I have not with other vessels.

Via the CCTVs, the ODS is seen normally, and in external view it's look normal as well.

[Picture for illustration](https://media.discordapp.net/attachments/637167278554742785/1135170473269923910/image.png)

**Comment by GLS-SSV** [comment]
Hi!
Thanks for the report, but this is a [know issue](https://www.orbiter-forum.com/threads/space-shuttle-vessel.37856/post-609912), which is "corrected" for the next version.

**Comment by GLS-SSV** [comment]
Fixed in v1.7.
