### ISSUE TITLE
Payload Bay Radiator system too slow

### ISSUE THREAD

**Issue by daves-ssu** [GLS-SSV/SSV#15]
Through my own testing I have found that the PLB Radiator system operates too slowly compared to the real-world hardware. This is true for both the latches and the panels themselves. They take about twice as long as they should to operate, with the historical operation times having been 24 seconds for the latches and 38 seconds for the panels.

**Comment by GLS-SSV** [comment]
Mechanism times, not just in the PLBDs, were affected by a number of factors, and although the actual times were usually faster than expected, they were also situations when they were slower. This project uses the expected times to average out such variations and avoid complicating the subsystems with variable times per vehicle or time frame.
