### ISSUE TITLE
APU sounds audible in vacuum in cockpit view

### ISSUE THREAD

**Issue by daves-ssu** [GLS-SSV/SSV#16]
The APU sounds (start up, operation and shut down) are all audible in space. This goes against the laws of physics doesn't it? The APUs should not be heard while in space and they should be pretty faint even on the ground, given the distance and the amount of insulation between them and the crew module.

**Comment by GLS-SSV** [comment]
Can't reproduce, works as intended (EXTERNAL_ONLY_FADED_MEDIUM). Need more info (situation, scenario, etc) or else there is nothing to do.

**Comment by daves-ssu** [comment]
I guess you don't have it loud enough. I can clearly hear the chugging from the APUs while in VC mode. Could be an OrbiterSound issue.

**Comment by GLS-SSV** [comment]
I had the volume as loud as I could tolerate, and could only hear silence outside, AC and switches inside. Tested all 4 combinations of OS4/5 build/pluggin, all with the same result.

**Comment by daves-ssu** [comment]
Could you maybe mute the AC to see if you can hear it? It's very faint but if you can't still hear it, I guess you could close the issue.

**Comment by GLS-SSV** [comment]
Can't reproduce.
