### ISSUE TITLE
OMS engine nozzles are brown when they should be grey

### ISSUE THREAD

**Issue by daves-ssu** [GLS-SSV/SSV#19]
Something I have noticed is that the OMS engine nozzles are brown when they should be grey. After doing some checking it seems to be due them sharing material with with the RCS jet nozzles.

**Comment by GLS-SSV** [comment]
Looks gray here, both in MOGE and D3D9. The OME material isn't perfect, but it works for now and will be improved in the future.

**Comment by daves-ssu** [comment]
Looking at the mesh again and it seems my mind must have been playing tricks on me as they have the proper dark grey color. Although, the materials should be separated as the even brand new the RCS jets had a brown outer perimeter with the nozzle interior being a greenish-grey color as shown in this photo of Discovery in the DFRC MDD still mated to the Overland Transporter ahead of having the MDD sling attached.
![STS41D-036C-EC83-27080b-11 5 83](https://github.com/GLS-SSV/SSV/assets/107274810/a84e7bf6-fd9b-46dc-86c4-ebcb70645274)
