### ISSUE TITLE
OV Forward Fuselage texture mapping issue

### ISSUE THREAD

**Issue by daves-ssu** [GLS-SSV/SSV#21]
So I'm working on a set of high resolution textures for Columbia and Challenger and when I got to the canopy area of the forward fuselage, I ran into the issues shown in the circles in the attached screenshot with the horizontal tile gaps. Any way the upper section texture map could be adjusted to provide a better transition between the sides and the top?

![SSV_OV_FF_texture_map_issue](https://github.com/GLS-SSV/SSV/assets/107274810/30ea0936-cc70-47f8-83d4-186eafbb37a8)

**Comment by GLS-SSV** [comment]
I'm sorry, but the model and textures are frozen in the short term. The current priority is code.
